### ISSUE TITLE
Can I create a BTIP for this repository?

### ISSUE THREAD

**Issue by ghost** [lmatteis/torrent-net#5]
Hey y'all!

What an incredible project! 

*What do you all think about me creating a [BTIP](https://github.com/bittorrent/BTIPs)¹ for him? Can I create a BTIP for this repository?*

#### ***why do you ask that?***
1. I would like to contribute to this project and the technical specification came to me as my first idea.
2. There may be many projects inspired by BTIP.
3. I'm an experientialist - that means I'm constantly looking for original ideas and want to contribute in different ways to free and open projects.
4. BTIP can be used as a standard in the "software industry" and can therefore be used for commercial (or academic or even personal, as long as it is a "standard") purposes.
5. I don't want to infringe on any copyright or even intellectual rights, so I ask.
6. I'm not promising anything, just asking if this would be possible to do with everyone's collaboration in this scenario I describe. 
7. I don't know if BTIP will be accepted when I write and publish it, but in any case it is something I will develop, create and try to do.
8. Software may no longer be produced and in this scenario, but when we have a technical specification it is easier to maintain than software.

#### ***references***

[1] BitTorrent File System Improvement Proposals (BTIPs) describe standards for the BTFS platform, including core protocol specifications and client APIs.

*What do you think about me creating a [BTIP](https://github.com/bittorrent/BTIPs)¹ for him? Can I create a BTIP for this repository? Do I have permission from the software creator and this community to create a technical specification in this repository?*

**Comment by en3r0** [comment]
Sounds like it is worth a shot!

**Comment by ghost** [comment]
Hi @en3r0, how are you?

**Comment by en3r0** [comment]
Hi @nichdemos  I am well, and yourself?

**Comment by ghost** [comment]
> Hi @nichdemos I am well, and yourself?

Hi @en3r0, I am well. I saw some open source projects: [awesome-distributed](https://github.com/en3r0/awesome-distributed) and [legittorrents.info](https://github.com/en3r0/legittorrents.info) ... you have and I want to help. Would you like to hear my ideas?

Also, thanks for the brief comment on my idea in this issue.

**Comment by en3r0** [comment]
@nichdemos sure thing.

**Comment by ghost** [comment]
> @nichdemos sure thing.

I forked it today: [nichdemos/awesome-distribute](https://github.com/nichdemos/awesome-distributed), and I'm going to upload some interesting software on awesome-distributed. There are cool projects like these that you didn't include on the list and that I consider good and important:
- [cjb/GitTorrent](https://github.com/cjb/GitTorrent): *"A decentralization of GitHub using BitTorrent and Bitcoin"*
- [legittorrents.info](https://github.com/en3r0/legittorrents.info): *"I started Legit Torrents in the Fall of 2005. I was still in high school and back then there was no 100% legal torrent tracker that anyone could easily submit to. There was legaltorrents.com, but if memory serves me correctly, it was more of a curated thing."*
- [lg/murder](https://github.com/lg/murder): *"Large scale server deploys using BitTorrent and the BitTornado library (NOTE: project no longer maintained)"*
- [lmatteis/torrent-net](https://github.com/lmatteis/torrent-net): *"Distributed search engines using BitTorrent and SQLite"*
- [russss/Herd](https://github.com/russss/Herd): *"A single-command bittorrent distribution system, based on Twitter's Murder"*

***faq***
- What do you think about me submitting a pull-request today and now at awesome-distributed? 
- Can these software or websites I listed be added to awesome-distributed?
- Does what I describe here make sense?

**Comment by en3r0** [comment]
@nichdemos nice ideas, I have not updated the list in years, feel free to submit a pull request.

**Comment by ghost** [comment]
> @nichdemos nice ideas, I have not updated the list in years, feel free to submit a pull request.

I'm happy with your message and I'll send the pull-request now. And I hope we will work together on new open and free projects if you want, have time or think my ideas are good. And if we can benefit together (win-win) together with all people.

**Comment by ghost** [comment]
Hey y'all! I launched the idea and await feedback: [BTIP: BTQL(BitTorrent Query Language)?](https://github.com/bittorrent/sqltorrent/issues/3). Please, help-me.

**Comment by en3r0** [comment]
> Hey y'all! I launched the idea and await feedback: [BTIP: BTQL(BitTorrent Query Language)?](https://github.com/bittorrent/sqltorrent/issues/3). Please, help-me.

Looks good from a quick glance!

**Comment by ghost** [comment]
Hi @en3r0, thanks for comment here!

> Looks good from a quick glance!

But please comment on the issue here too: [BitTorrent Query Language](https://github.com/bittorrent/sqltorrent/issues/3).
